name: Deploy Frontend

on:
  push:
    branches:
      - main # Trigger the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker-compose stop frontend-frontend-1
            docker-compose rm -f frontend-frontend-1
            [ -d "frontend" ] && [ "$(ls -A frontend)" ] && (cd frontend && git pull) || git clone git@github.com:sameerabit/election-survey-app.git frontend
            cd frontend && docker-compose build --no-cache && docker-compose up --remove-orphans -d
